= Run a multi-container web application with Podman

In this exercise, you will learn to create and run a multi-container application with MySQL and Apache in a pod with Podman.

[#mysql]
== Run a MySQL container

**1) Run a MySQL container using persistent storage as in Lab 1.**

[source,bash,subs="+macros,+attributes"]
----
$ sudo podman run -d  -v /var/local/mysql:/var/lib/mysql/data -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=upm -e MYSQL_ROOT_PASSWORD=rootpass  rhscl/mysql-57-rhel7
----

[#apache]
== Run an Apache container

**2) Create an iamge of Apache with PHP-MySQL using the following Dockerfile**

[source,dockerfile,subs="+macros,+attributes"]
----
FROM docker.io/library/php:7.0-apache

EXPOSE 80 

RUN docker-php-ext-install -j$(nproc) mysqli

COPY ./src/ /var/www/html/
----

Create a directory src, and crete there a index.php with the following content:

[source,php,subs="+macros,+attributes"]
----
<?php
// Connecting, selecting database
$mysqli = new mysqli($_ENV["MYSQL_HOST"], $_ENV["MYSQL_USER"], $_ENV["MYSQL_PASSWORD"], $_ENV["MYSQL_DATABASE"]);

if ($mysqli->connect_errno) {
  echo "Failed to connect to database";
  echo "Error: " . $mysqli->connect_error . "\n";
}

// Performing SQL query
$sql = 'SELECT * FROM ' . $_ENV["MYSQL_TABLE"];

if (!$result = $mysqli->query($sql)) {
    echo "Error executing the query " . $sql . "\n";
    echo "Error: " .  $mysqli->error . "\n";
}

echo "<ul>\n";
while ($student = $result->fetch_assoc()) {
    echo "<li>Student : " . $student['name'] . "</li>\n";
}
echo "</ul>\n";

?>
----

**Build the Dockerfile, and run a container using the image, setting the env MySQL_HOST to 127.0.0.1 and listening in localhost on port 80.**

[source,bash,subs="+macros,+attributes"]
----
$ sudo podman build -t myphp:v1 .
$ sudo podman run -d -e MYSQL_HOST=127.0.0.1 -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=upm -e MYSQL_ROOT_PASSWORD=rootpass -e MYSQL_TABLE=students -p 8080:80  myphp:v1
----

**Do a curl to http://127.0.0.1:8080. Are you able to see the database content? Why not?**


[#pod]
== Create a pod with Podman

**3) Pods created by Podman have three default shared namespaces: net, uts, and ipc.  Stop all the containers created before, and create a new pod exposing port 8080 and binding to containers port 80**

[source,bash,subs="+macros,+attributes"]
----
$ sudo podman pod create --name myapp -p 8080:80
----

[#multicontainers]
== Run containter in a pod with Podman

**4) Run the MySQL and Apache containers inside the pod you've just created.**

[source,bash,subs="+macros,+attributes"]
----
$ sudo podman run -d  -v /var/local/mysql:/var/lib/mysql/data -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=upm -e MYSQL_ROOT_PASSWORD=rootpass --pod myapp rhscl/mysql-57-rhel7
$ sudo podman run -d -e MYSQL_HOST=127.0.0.1 -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=upm -e MYSQL_ROOT_PASSWORD=rootpass -e MYSQL_TABLE=students -p 8080:80 --pod myapp myphp:v1
----


**Do a curl to http://127.0.0.1:8080. Are you able to see the database content? **