= Deploying multi-container applications in Openshift

[.text-center.strong]
== Introduction

Deploying container applications with Podman is the second of part of **Autoscaling serverless applications in Openshift** workshop to get familiar with containers and autoscaling serverless applications in Openshift. You'll start creating a multi-container web application with Podman. Then, you'll create a MySQL application in Openshift. Finally, you'll create an Apache application and you'll connect it with the MySQL application on Openshift.

[.tiles.browse]
== Exercises

=== 1. Run a multi-container web application with Podman

Create and run a multi-container application with MySQL and Apache in a pod with Podman.

xref:02-multi-container.adoc[Start]

=== 2. Create a MySQL application in Openshift

Create a MySQL application using the Openshift Web Console.

xref:03-mysql.adoc[Start]

=== 3. Connect an Apache with a MySQL application in Openshift

Create a PHP application, and connect to the MySQL application using the Openshift Web Console. Scale up the application.

xref:04-apache.adoc[Start]